db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=BAKERYVIPXILIP;encrypt=false;trustServerCertificate=true
db.user=drac
db.password=2908Drac@